<div class="register">
    
    <form method="POST" action="/cadastro/novo">
        <div class="input">
            <input type="text" name="nome" placeholder="Nome" autocomplete="off">
        </div>

        <div class="input">
            <input type="email" name="email" placeholder="E-mail" autocomplete="off">
        </div>

        <div class="input">
            <input type="tel" name="fone" placeholder="Telefone" autocomplete="off">
        </div>

        <div class="input">
            <input type="text" name="cpf" placeholder="CPF" autocomplete="off">
        </div>

        <div class="input">
            <input type="text" name="endereco" placeholder="Endereço" autocomplete="off">
        </div>

        <div class="fieldset">
            <div class="input cidade">
                <input type="text" name="cidade" placeholder="Cidade" autocomplete="off">
            </div>

            <div class="input estado">
                <input type="text" name="estado" placeholder="Estado" maxlength="2" autocomplete="off">
            </div>
        </div>

        <button type="submit" id="submit_cadastro"></button>
        
        <!-- ////////////////// REMOVER /////////////////// -->
        <!-- <button class="btn" type="submit">Cadastrar</button> -->
        <!-- ////////////////// REMOVER /////////////////// -->
    </form>

</div>
<!-- 
<div class="notification alert hide">
    <div class="notification-inner">
        <div class="msg">Algo esta dando muuuito errado!</div>
    </div>
</div> -->