<style>
.form-login {
    position: absolute;
    box-sizing: border-box;
    width: 80vw;
    max-width: 500px;
    z-index: 99;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}
.form-login .input input {
    border-radius: 6px;
    box-shadow: inset 0 5px 8px rgba(0,0,0,.5);
}
</style>

<form class="form-login" method="GET" action="/login">
    <div class="input">
        <input type="email" name='email' placeholder='Digite um e-mail cadastrado'>
    </div>
</form>