<style>
.logoff {
    text-decoration: none;
    position: absolute;
    z-index: 99;
    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%);
    background: #a7a7a7;
    overflow: hidden;

    width: 100px;
    height: 100px;
    border-radius: 50%;
    opacity: 1;
    box-shadow: inset 0 -2px 10px rgba(0, 0, 0, 0.7);
    border: none;

    transition: background .23s;
}
.logoff:before {
    content: "";
    float: left;
    width: 50px;
    height: 50px;
    border-radius: 50%;
    border: 10px solid #4d4d4d;
    margin: 15px;
}
.logoff:after {
    content: "";
    float: left;
    width: 10px;
    height: 50px;
    background: #4d4d4d;
    position: absolute;
    top: 10px;
    left: 38px;
    border: 7px solid #a7a7a7;
    border-top: none;

    transition: border .23s;
}
/*
.logoff:hover:before { border-color: orangered;}
.logoff:hover:after { background: orangered; }
*/
</style>

<div class="logoff"></div>